// Document Types Configuration for R&D Tax Credit Claims
// Based on IRS requirements and 2024-2025 updates
// Categories: Financial, Technical, Employee, and Supporting Documentation

export const documentTypes = {
  // CORE IRS REQUIRED DOCUMENTS
  coreRequirements: {
    category: 'Core IRS Requirements',
    required: true,
    importance: 'critical',
    documents: [
      {
        id: 'form_6765',
        name: 'Form 6765',
        description: 'Credit for Increasing Research Activities (will be generated)',
        required: false,
        acceptedFormats: ['.pdf'],
        maxSize: 10485760, // 10MB
        icon: '📋',
        irsRequired: false,
        autoGenerated: true
      },
      {
        id: 'federal_tax_current',
        name: 'Current Year Federal Tax Return',
        description: 'Form 1120, 1120S, 1065, or 1040 Schedule C',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 10485760,
        icon: '📄',
        irsRequired: true
      },
      {
        id: 'federal_tax_prior',
        name: 'Prior Year Federal Tax Return',
        description: 'Previous year Form 1120, 1120S, 1065, or 1040 Schedule C',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 10485760,
        icon: '📄',
        irsRequired: true
      }
    ]
  },

  // FINANCIAL DOCUMENTATION
  financialDocuments: {
    category: 'Financial Documentation',
    required: true,
    importance: 'high',
    documents: [
      {
        id: 'w2_forms',
        name: 'W-2 Forms',
        description: 'W-2s for all employees involved in R&D activities',
        required: false,
        acceptedFormats: ['.pdf', '.jpg', '.png', '.zip'],
        maxSize: 20971520, // 20MB
        icon: '💰',
        irsRequired: false
      },
      {
        id: 'payroll_registers',
        name: 'Payroll Registers',
        description: 'Detailed payroll records showing employee wages and hours',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.csv'],
        maxSize: 10485760,
        icon: '📊',
        irsRequired: false
      },
      {
        id: 'general_ledger',
        name: 'General Ledger',
        description: 'Chart of accounts with R&D expense details',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.csv'],
        maxSize: 10485760,
        icon: '📒',
        strengthensCase: true
      },
      {
        id: 'expense_reports',
        name: 'R&D Expense Reports',
        description: 'Detailed breakdown of supplies, contract research, and other R&D costs',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.csv'],
        maxSize: 10485760,
        icon: '💳',
        strengthensCase: true
      },
      {
        id: 'contract_research',
        name: 'Contract Research Agreements',
        description: 'Agreements with third-party contractors for R&D work',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx'],
        maxSize: 10485760,
        icon: '📑',
        strengthensCase: true
      }
    ]
  },

  // TECHNICAL DOCUMENTATION
  technicalDocuments: {
    category: 'Technical Documentation',
    required: true,
    importance: 'high',
    documents: [
      {
        id: 'project_records',
        name: 'Project Records',
        description: 'Documentation demonstrating the four-part test compliance',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx', '.zip'],
        maxSize: 20971520,
        icon: '🔬',
        irsRequired: false
      },
      {
        id: 'lab_notebooks',
        name: 'Lab Notebooks / Development Logs',
        description: 'Contemporaneous records of experiments, testing, and development',
        required: false,
        acceptedFormats: ['.pdf', '.jpg', '.png', '.zip'],
        maxSize: 20971520,
        icon: '📔',
        strengthensCase: true
      },
      {
        id: 'design_documents',
        name: 'Design Documents & Specifications',
        description: 'Technical specs, architecture diagrams, engineering drawings',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx', '.dwg', '.zip'],
        maxSize: 20971520,
        icon: '📐',
        strengthensCase: true
      },
      {
        id: 'patents_applications',
        name: 'Patents & Patent Applications',
        description: 'Filed patents or patent applications related to R&D',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx'],
        maxSize: 10485760,
        icon: '🏆',
        strengthensCase: true
      },
      {
        id: 'test_results',
        name: 'Test Results & Failure Analysis',
        description: 'Documentation of testing procedures, results, and iterations',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.csv', '.zip'],
        maxSize: 20971520,
        icon: '🧪',
        strengthensCase: true
      }
    ]
  },

  // EMPLOYEE DOCUMENTATION
  employeeDocuments: {
    category: 'Employee Documentation',
    required: true,
    importance: 'high',
    documents: [
      {
        id: 'employee_timesheets',
        name: 'Employee Timesheets',
        description: 'Time tracking records showing project allocation',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.csv', '.zip'],
        maxSize: 20971520,
        icon: '⏱️',
        irsRequired: false
      },
      {
        id: 'job_descriptions',
        name: 'Job Titles & Descriptions',
        description: 'Employee roles, responsibilities, and department assignments',
        required: false,
        acceptedFormats: ['.pdf', '.xlsx', '.doc', '.docx'],
        maxSize: 10485760,
        icon: '👥',
        irsRequired: false
      },
      {
        id: 'org_chart',
        name: 'Organizational Chart',
        description: 'Company structure showing reporting relationships',
        required: false,
        acceptedFormats: ['.pdf', '.ppt', '.pptx', '.jpg', '.png'],
        maxSize: 10485760,
        icon: '🏢',
        strengthensCase: true
      },
      {
        id: 'performance_reviews',
        name: 'Performance Reviews',
        description: 'Employee evaluations mentioning R&D activities',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx', '.zip'],
        maxSize: 20971520,
        icon: '📈',
        strengthensCase: true
      }
    ]
  },

  // SUPPORTING DOCUMENTATION
  supportingDocuments: {
    category: 'Supporting Documentation',
    required: false,
    importance: 'medium',
    documents: [
      {
        id: 'meeting_minutes',
        name: 'Meeting Minutes & Notes',
        description: 'Technical meetings discussing R&D challenges and solutions',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx', '.zip'],
        maxSize: 10485760,
        icon: '📝',
        strengthensCase: true
      },
      {
        id: 'email_correspondence',
        name: 'Email Correspondence',
        description: 'Technical discussions and project communications',
        required: false,
        acceptedFormats: ['.pdf', '.eml', '.msg', '.zip'],
        maxSize: 20971520,
        icon: '📧',
        strengthensCase: true
      },
      {
        id: 'project_photos',
        name: 'Project Photos/Videos',
        description: 'Visual documentation of prototypes, experiments, or development',
        required: false,
        acceptedFormats: ['.jpg', '.png', '.mp4', '.mov', '.zip'],
        maxSize: 52428800, // 50MB
        icon: '📸',
        strengthensCase: true
      },
      {
        id: 'invoices_receipts',
        name: 'Supply Invoices & Receipts',
        description: 'Purchase records for R&D supplies and materials',
        required: false,
        acceptedFormats: ['.pdf', '.jpg', '.png', '.zip'],
        maxSize: 20971520,
        icon: '🧾',
        strengthensCase: true
      }
    ]
  },

  // NEW 2025 SECTION G REQUIREMENTS (for companies with >$1.5M QREs)
  sectionGRequirements: {
    category: '2025 Section G Requirements',
    required: false, // Only for large companies
    importance: 'high',
    applicability: 'Required for companies with >$1.5M in qualified research expenses',
    documents: [
      {
        id: 'business_component_breakdown',
        name: 'Business Component Breakdown',
        description: '80% of QREs or top 50 business components with detailed descriptions',
        required: false,
        acceptedFormats: ['.xlsx', '.csv', '.pdf'],
        maxSize: 10485760,
        icon: '📊',
        new2025: true
      },
      {
        id: 'officer_wage_breakdown',
        name: 'Officer Wage Breakdown',
        description: 'Separate reporting of officer wages involved in R&D',
        required: false,
        acceptedFormats: ['.xlsx', '.csv', '.pdf'],
        maxSize: 10485760,
        icon: '💼',
        new2025: true
      },
      {
        id: 'methodology_documentation',
        name: 'R&D Methodology Documentation',
        description: 'Detailed explanation of R&D identification and calculation methods',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx'],
        maxSize: 10485760,
        icon: '📋',
        new2025: true
      }
    ]
  }
};

// Helper function to get all documents as a flat array
export const getAllDocuments = () => {
  const allDocs = [];
  Object.values(documentTypes).forEach(category => {
    category.documents.forEach(doc => {
      allDocs.push({
        ...doc,
        category: category.category,
        categoryImportance: category.importance,
        categoryRequired: category.required
      });
    });
  });
  return allDocs;
};

// Helper function to get required documents only
export const getRequiredDocuments = () => {
  const requiredDocs = [];
  Object.values(documentTypes).forEach(category => {
    category.documents.forEach(doc => {
      if (doc.required || doc.irsRequired) {
        requiredDocs.push({
          ...doc,
          category: category.category,
          categoryImportance: category.importance
        });
      }
    });
  });
  return requiredDocs;
};

// Helper function to get documents that strengthen the case
export const getStrengtheningDocuments = () => {
  const strengtheningDocs = [];
  Object.values(documentTypes).forEach(category => {
    category.documents.forEach(doc => {
      if (doc.strengthensCase) {
        strengtheningDocs.push({
          ...doc,
          category: category.category,
          categoryImportance: category.importance
        });
      }
    });
  });
  return strengtheningDocs;
};

// Helper function to get 2025 specific requirements
export const getSection2025Requirements = () => {
  const section2025 = [];
  Object.values(documentTypes).forEach(category => {
    category.documents.forEach(doc => {
      if (doc.new2025) {
        section2025.push({
          ...doc,
          category: category.category,
          applicability: category.applicability
        });
      }
    });
  });
  return section2025;
};

// Helper function to check if company needs Section G reporting
export const needsSectionGReporting = (qualifiedResearchExpenses, grossReceipts) => {
  return qualifiedResearchExpenses > 1500000 || grossReceipts > 50000000;
};

export default documentTypes;